services:
    console.installer.command_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: console.installer.command }

    console.installer.command.install:
        class: phpbb\install\console\command\install
        arguments:
            - @language
            - @installer.helper.iohandler_factory
            - @installer.installer.install
        tags:
            - { name: console.installer.command }
